name: lectorium-dev

services:
  app-mobile:
    user: "${DEVCONTAINER_USER_ID:-1000}:${DEVCONTAINER_USER_GID:-100}"
    build:
      context: ../..
      dockerfile: .devcontainer/apps-mobile/Dockerfile
      args:
        - USER_ID=${DEVCONTAINER_USER_ID:-1000}
        - USER_NAME=${DEVCONTAINER_USER_NAME:-dev}
        - GROUP_ID=${DEVCONTAINER_USER_GID:-100}
    ports:
      - 5173
    volumes:
      - ../../modules/apps/mobile:/akd-studios/lectorium/apps/mobile
