name: lectorium

services:
  gateway:
    build:
      context: ../..
      dockerfile: .devcontainer/services-gateway/Dockerfile
      args:
        - USER_ID=${DEVCONTAINER_USER_ID:-1000}
        - USER_NAME=${DEVCONTAINER_USER_NAME:-dev}
        - GROUP_ID=${DEVCONTAINER_USER_GID:-100}
    volumes:
      - ../../modules/services/gateway:/akd-studios/lectorium/services/gateway
    networks:
      - lectorium
    ports:
      - "80:80"

networks:
  lectorium:
