vars:
  VERSION:
    default: "0.0.1"
  BUILD_ID:
    default: 1
  DEVELOPMENT_TEAM:
    default: "YourTeamID"

platforms:
  # ios:
  #   buildNumber: $GITHUB_RUN_ID
  android:
    versionName: $VERSION
    versionCode: $BUILD_ID
  ios:
    targets:
      App:
        buildSettings:
          DEVELOPMENT_TEAM: $DEVELOPMENT_TEAM
