from lectorium.index.tasks.get_words_to_index import get_words_to_index
from lectorium.index.tasks.get_words_stems import get_words_stems
from lectorium.index.tasks.update_index_document import update_index_document
