name: lectorium

# -------------------------------------------------------------------------- #
#                                  Services                                  #
# -------------------------------------------------------------------------- #

services:
  api:
    image: ghcr.io/akdasa-studios/lectorium-api:staging
    volumes:
      - ../data/keys/jwt/:/etc/lectorium/keys/
 
  landing:
    image: ghcr.io/akdasa-studios/lectorium-landing:staging

  mobile-web:
    image: ghcr.io/akdasa-studios/lectorium-mobile-web:staging

  admin:
    image: ghcr.io/akdasa-studios/lectorium-admin:staging

  airflow-webserver:
    image: ghcr.io/akdasa-studios/lectorium-airflow:staging

  airflow-scheduler:
    image: ghcr.io/akdasa-studios/lectorium-airflow:staging

  airflow-worker:
    image: ghcr.io/akdasa-studios/lectorium-airflow:staging

  airflow-triggerer:
    image: ghcr.io/akdasa-studios/lectorium-airflow:staging

  airflow-init:
    image: ghcr.io/akdasa-studios/lectorium-airflow:staging

  couchdb:
    image: ghcr.io/akdasa-studios/lectorium-couchdb:staging

  couchdb-init:
    image: ghcr.io/akdasa-studios/lectorium-couchdb-init:staging

  gateway:
    image: ghcr.io/akdasa-studios/lectorium-gateway:staging
    volumes:
      - ../data/gateway/certs:/workspaces/lectorium/data/gateway/certs
    environment:
      - CONFIG_TYPE=release

    