name: lectorium

# -------------------------------------------------------------------------- #
#                                  Services                                  #
# -------------------------------------------------------------------------- #

services:
  admin:
    image: ghcr.io/akdasa-studios/lectorium-admin:staging
    ports:
      - "80:80"

  couchdb:
    image: ghcr.io/akdasa-studios/lectorium-couchdb:staging

  couchdb-init:
    image: ghcr.io/akdasa-studios/lectorium-couchdb-init:staging

  airflow-webserver:
    image: ghcr.io/akdasa-studios/lectorium-airflow:staging

  airflow-scheduler:
    image: ghcr.io/akdasa-studios/lectorium-airflow:staging

  airflow-worker:
    image: ghcr.io/akdasa-studios/lectorium-airflow:staging

  airflow-triggerer:
    image: ghcr.io/akdasa-studios/lectorium-airflow:staging

  airflow-init:
    image: ghcr.io/akdasa-studios/lectorium-airflow:staging
