name: lectorium

services:

  dev:
    image: mcr.microsoft.com/devcontainers/base:noble
    command: sleep 365d
    ports:
      - "80:80"
      - "443:443"
    networks:
      - lectorium
    volumes:
      - ../:/workspaces/lectorium
      - /tmp/lectorium:/tmp/lectorium
    depends_on:
      - couchdb
      - postgres
      - redis
      
  # -------------------------------------------------------------------------- #
  #                                  Services                                  #
  # -------------------------------------------------------------------------- #

  api:
    build:
      context: ../modules/
      dockerfile: ./services/api/Dockerfile
    volumes:
      - ../data/keys/jwt/:/etc/lectorium/keys/


  admin:
    build:
      context: ../modules/
      dockerfile: ./apps/admin/Dockerfile

  gateway:
    build:
      context: ../modules/
      dockerfile: ./services/gateway/Dockerfile
    volumes:
      - ../data/gateway/certs:/workspaces/lectorium/data/gateway/certs

  couchdb:
    build:
      context: ../modules/
      dockerfile: ./services/couchdb/service/Dockerfile

  couchdb-init:
    build:
      context: ../modules/
      dockerfile: ./services/couchdb/init/Dockerfile
    environment:
      LECTORIUM_CONTENT_MANAGER_EMAIL: contentManager@lectorium.dev
      LECTORIUM_CONTENT_MANAGER_PASSWORD: contentManager

  postgres:
    environment:
      POSTGRES_USER: lectorium
      POSTGRES_PASSWORD: lectorium
      POSTGRES_DB: lectorium

  airflow-webserver:
    build:
      context: ../modules/
      dockerfile: ./services/airflow/Dockerfile

  airflow-scheduler:
    build:
      context: ../modules/
      dockerfile: ./services/airflow/Dockerfile

  airflow-worker:
    build:
      context: ../modules/
      dockerfile: ./services/airflow/Dockerfile

  airflow-triggerer:
    build:
      context: ../modules/
      dockerfile: ./services/airflow/Dockerfile

  airflow-init:
    build:
      context: ../modules/
      dockerfile: ./services/airflow/Dockerfile
    environment:
      _AIRFLOW_DB_MIGRATE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: lectorium
      _AIRFLOW_WWW_USER_PASSWORD: lectorium
