name: lectorium

services:

  auth:
    image: ghcr.io/akdasa-studios/lectorium-auth:latest
    restart: always

  brahma:
    image: ghcr.io/akdasa-studios/lectorium-brahma:latest
    restart: always

  database:
    image: ghcr.io/akdasa-studios/lectorium-database:latest
    restart: always

  database-bootstrap:
    image: ghcr.io/akdasa-studios/lectorium-database-bootstrap:latest
    restart: no

  gateway:
    image: ghcr.io/akdasa-studios/lectorium-gateway:latest
    command: ["nginx", "-c", "/akd-studios/lectorium/services/gateway/envs/prod/_root.conf", "-g", "daemon off;"]
    restart: always
    depends_on:
      database:
        condition: service_healthy
      signed-url-generator:
        condition: service_started

  signed-url-generator:
    image: ghcr.io/akdasa-studios/lectorium-signed-url-generator:latest
    restart: always


  vayu-init:
    image: ghcr.io/akdasa-studios/lectorium-vayu:latest

  vayu-webserver:
    image: ghcr.io/akdasa-studios/lectorium-vayu:latest
    restart: always

  vayu-scheduler:
    image: ghcr.io/akdasa-studios/lectorium-vayu:latest
    restart: always

  vayu-worker:
    image: ghcr.io/akdasa-studios/lectorium-vayu:latest
    restart: always

  vayu-triggerer:
    image: ghcr.io/akdasa-studios/lectorium-vayu:latest
    restart: always
