name: lectorium

# -------------------------------------------------------------------------- #
#                                  Services                                  #
# -------------------------------------------------------------------------- #

services:
  admin:
    image: ghcr.io/akdasa-studios/lectorium-admin:staging
    ports:
      - "80:80"
