name: lectorium

services:
  database:
    build:
      context: ../modules/services/database/modules/database/
      dockerfile: Dockerfile
    environment:
      - COUCHDB_USER=lectorium
      - COUCHDB_PASSWORD=lectorium
    ports:
      - "5984:5984"

  database-bootstrap:
    build:
      context: ../modules/services/database/modules/bootstrap/
      dockerfile: Dockerfile

  gateway:
    build:
      context: ../modules/services/gateway
      dockerfile: Dockerfile

  signed-url-generator:
    build:
      context: ../modules/services/signed-url-generator
      dockerfile: Dockerfile


