name: '👷‍♂️ Build Container'
description: 'Builds a Docker container'

runs:
  using: 'composite'
  steps:
    - name: 🐳 Setup Docker
      uses: docker/setup-buildx-action@v2

    - name: 🔑 Log into registry ${{ inputs.registry }}
      uses: docker/login-action@v2
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: 👷‍♂️ Build Image
      uses: docker/build-push-action@v6
      with:
        context: ./modules
        file: {{ inputs.file }}
        load: true
