name: CouchDB

on:
  push:
    branches:
      - main
    paths:
      - "modules/services/couchdb/**"
      - ".github/workflows/couchdb-build.yml"
      - ".github/workflows/couchdb-deploy-staging.yml"

env:
  REGISTRY: ghcr.io
  ORGANIZATION: akdasa-studios

jobs:
  deploy:
    environment:
      name: staging
    name: 🚀 Deploy to Staging
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      
      - name: 👷‍♂️ Build Container
        uses: ./.github/actions/build-container
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          file: modules/services/couchdb/service/Dockerfile
          tags: |
            ${{ env.REGISTRY }}/${{ env.ORGANIZATION }}/lectorium-couchdb:staging

      - name: ⬆️ Push staging Image
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.ORGANIZATION }}/lectorium-couchdb:staging
